services:
  backend:
    build: .
    container_name: backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    environment:
      - debug=0
    depends_on:
      - redis
    volumes:
      - static:/static  

  redis:
    image: "redis"
    ports:
      - 6379

  frontend:
    build: ./frontend
    container_name: fe
    command: npm run dev
    depends_on:
      - backend
    ports:
      - "5173:5173"

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  static: