services:
  backend:
    build: .
    container_name: backend
    command: sh -c "python3 manage.py migrate && gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120"
    depends_on:
      - redis
    environment:
      - DATA_URL=https://data.bhmohit.dev
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge