services:
  backend:
    build: .
    container_name: backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - debug=0
    depends_on:
      - redis

  redis:
    image: "redis"
    ports:
      - 6379

  frontend:
    build: ./frontend
    container_name: fe
    command: npm run dev
    depends_on:
      - backend
    ports:
      - "5173:5173"