services:
  backend:
    build: .
    container_name: backend
    command: sh -c "python3 manage.py migrate && gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120"
    depends_on:
      - redis
    volumes:
      - static:/static
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  # frontend:
  #   build: ./frontend
  #   container_name: frontend
  #   command: npm run build
  #   environment:
  #     - REACT_APP_BACKEND=http://nginx
  #   volumes:
  #     - ./frontend/dist:/usr/share/nginx/html
  #   networks:
  #     - app-network

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - static:/static
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  static: